pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public/
  environment:
    name: production
    url: https://sounwavze.techmunchies.net
  only:
    - master@techmunchies/sounwavze.com
